spring:
  application:
    name: hrforce
  profiles:
    active: dev
  config:
    import: "optional:configserver:http://localhost:8888"
  autoconfigure:
    exclude: org.springframework.boot.security.autoconfigure.UserDetailsServiceAutoConfiguration